# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: go121
service: oidcservice
app_engine_apis: true

# Everything is in-memory so we use just one instance.
# If you need more all config, session, and log stores 
# will need to be made distributed.
manual_scaling:
  instances: 1

handlers:
- url: /.*
  secure: optional
  script: auto

env_variables:
  LOG_USERNAME:
  LOG_PASSWORD: